server:
  port: 8989
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ROOT
    url: jdbc:mysql://localhost:3306/cmfz
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
  redis:
    port: 7000
    database: 0
    host: 192.168.198.30
#    lettuce:
#      pool:
#        max-active: -1
#       max-idle: 8
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:com/baizhi/dao/*Mapper.xml